const categories = [
  'Information Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Marketing',
  'Sales',
  'Engineering',
  'Customer Service',
  'Human Resources',
  'Design',
  'Hospitality',
  'Retail',
  'Transportation',
  'Manufacturing',
  'Media & Communications',
  'Legal',
  'Science',
  'Construction',
  'Non-profit & Volunteering',
  'Other'
]
const subCategories = {
  'Information Technology': [
    'Web Development',
    'Mobile App Development',
    'UI/UX Design',
    'Software Engineering',
    'Data Science & Analytics',
    'DevOps & Cloud Computing',
    'Cybersecurity',
    'Database Administration',
    'Network Engineering',
    'IT Support',
    'Game Development',
    'Artificial Intelligence',
    'Business Intelligence',
    'IT Project Management',
    'Other IT Jobs'
  ],
  Healthcare: [
    'Nursing',
    'Physician',
    'Dentist',
    'Pharmacist',
    'Physical Therapist',
    'Medical Technologist',
    'Healthcare Administration',
    'Radiologic Technologist',
    'Occupational Therapist',
    'Mental Health Counselor',
    'Medical Assistant',
    'Speech Therapist',
    'Home Health Aide',
    'Other Healthcare Jobs'
  ],
  Finance: [
    'Accounting',
    'Financial Analyst',
    'Investment Banking',
    'Financial Planning',
    'Insurance',
    'Taxation',
    'Audit',
    'Actuary',
    'Credit Analyst',
    'Mortgage Officer',
    'Banking',
    'Financial Consulting',
    'Other Finance Jobs'
  ],
  Education: [
    'Teacher',
    'Professor',
    'Educational Administrator',
    'School Counselor',
    'Curriculum Developer',
    'Special Education Teacher',
    'Education Consultant',
    'Librarian',
    'Online Tutor',
    'Teaching Assistant',
    'Other Education Jobs'
  ],
  Marketing: [
    'Digital Marketing',
    'Social Media Marketing',
    'Content Marketing',
    'Product Marketing',
    'Brand Management',
    'Market Research',
    'Public Relations',
    'Advertising',
    'Email Marketing',
    'SEO Specialist',
    'Other Marketing Jobs'
  ],
  Sales: [
    'Sales Representative',
    'Sales Manager',
    'Account Executive',
    'Business Development',
    'Retail Sales',
    'Inside Sales',
    'Outside Sales',
    'Sales Consultant',
    'Sales Support',
    'Other Sales Jobs'
  ],
  Engineering: [
    'Mechanical Engineering',
    'Electrical Engineering',
    'Civil Engineering',
    'Software Engineering',
    'Aerospace Engineering',
    'Chemical Engineering',
    'Biomedical Engineering',
    'Environmental Engineering',
    'Industrial Engineering',
    'Materials Engineering',
    'Other Engineering Jobs'
  ],
  'Customer Service': [
    'Customer Support Representative',
    'Call Center Agent',
    'Technical Support',
    'Client Success Manager',
    'Customer Service Manager',
    'Customer Experience Specialist',
    'Help Desk Support',
    'Other Customer Service Jobs'
  ],
  'Human Resources': [
    'HR Generalist',
    'Recruiter',
    'HR Manager',
    'Talent Acquisition Specialist',
    'Compensation & Benefits Analyst',
    'Employee Relations Specialist',
    'Training & Development',
    'HR Consultant',
    'Other HR Jobs'
  ],
  Design: [
    'Graphic Designer',
    'UX/UI Designer',
    'Product Designer',
    'Interior Designer',
    'Industrial Designer',
    'Fashion Designer',
    'Motion Designer',
    'Visual Designer',
    'Other Design Jobs'
  ],
  Hospitality: [
    'Hotel Manager',
    'Chef',
    'Restaurant Manager',
    'Event Coordinator',
    'Tourism Manager',
    'Travel Agent',
    'Hospitality Specialist',
    'Catering Staff',
    'Other Hospitality Jobs'
  ],
  Retail: [
    'Store Manager',
    'Sales Associate',
    'Visual Merchandiser',
    'Inventory Manager',
    'Retail Buyer',
    'E-commerce Manager',
    'Retail Operations Manager',
    'Other Retail Jobs'
  ],
  Transportation: [
    'Truck Driver',
    'Delivery Driver',
    'Bus Driver',
    'Taxi Driver',
    'Courier',
    'Flight Attendant',
    'Shipping & Receiving Clerk',
    'Logistics Coordinator',
    'Other Transportation Jobs'
  ],
  Manufacturing: [
    'Production Worker',
    'Manufacturing Engineer',
    'Quality Control Inspector',
    'Assembler',
    'Machine Operator',
    'Production Supervisor',
    'Manufacturing Technician',
    'Other Manufacturing Jobs'
  ],
  'Media & Communications': [
    'Journalist',
    'Public Relations Specialist',
    'Content Writer',
    'Editor',
    'Copywriter',
    'Social Media Manager',
    'Media Planner',
    'Other Media & Communications Jobs'
  ],
  Legal: [
    'Lawyer',
    'Paralegal',
    'Legal Secretary',
    'Legal Assistant',
    'Legal Consultant',
    'Compliance Officer',
    'Legal Analyst',
    'Other Legal Jobs'
  ],
  Science: [
    'Research Scientist',
    'Laboratory Technician',
    'Biologist',
    'Chemist',
    'Physicist',
    'Environmental Scientist',
    'Data Scientist',
    'Other Science Jobs'
  ],
  Construction: [
    'Construction Worker',
    'Project Manager',
    'Architect',
    'Carpenter',
    'Civil Engineer',
    'Electrician',
    'Plumber',
    'Other Construction Jobs'
  ],
  'Non-profit & Volunteering': [
    'Fundraiser',
    'Program Coordinator',
    'Community Outreach Specialist',
    'Volunteer Coordinator',
    'Grant Writer',
    'Non-profit Manager',
    'Other Non-profit & Volunteering Jobs'
  ],
  Other: ['Other Jobs']
}
const locations = [
  'New York, USA',
  'Los Angeles, USA',
  'London, UK',
  'Toronto, Canada',
  'Sydney, Australia',
  'Paris, France',
  'Berlin, Germany',
  'Tokyo, Japan',
  'Beijing, China',
  'Mumbai, India',
  'São Paulo, Brazil',
  'Moscow, Russia',
  'Cairo, Egypt',
  'Johannesburg, South Africa',
  'Dubai, UAE',
  'Mexico City, Mexico',
  'Seoul, South Korea',
  'Rome, Italy',
  'Amsterdam, Netherlands',
  'Singapore, Singapore',
  'Stockholm, Sweden',
  'Zurich, Switzerland',
  'Istanbul, Turkey',
  'Bangkok, Thailand',
  'Helsinki, Finland',
  'Vienna, Austria',
  'Dublin, Ireland',
  'Auckland, New Zealand',
  'Santiago, Chile',
  'Lisbon, Portugal',
  'Madrid, Spain',
  'Oslo, Norway',
  'Warsaw, Poland',
  'Copenhagen, Denmark',
  'Budapest, Hungary',
  'Prague, Czech Republic',
  'Athens, Greece',
  'Jerusalem, Israel',
  'Hanoi, Vietnam',
  'Kuala Lumpur, Malaysia',
  'Wellington, New Zealand',
  'Cape Town, South Africa',
  'Vancouver, Canada',
  'Edinburgh, UK',
  'Melbourne, Australia',
  'Hamburg, Germany',
  'Brussels, Belgium',
  'Barcelona, Spain',
  'Riyadh, Saudi Arabia',
  'Osaka, Japan'
]
export { categories, locations, subCategories }
